Fix Simple CPU link
SimpleCPU requires link with tlm2c and dl
Fix error (CentOS 7) :

Linking CXX executable SimpleCPU_testbench
../libsimplecpu.so: undefined reference to `b_transport'
../libsimplecpu.so: undefined reference to `payload_set_command'
../libsimplecpu.so: undefined reference to `payload_get_size'
../libsimplecpu.so: undefined reference to `payload_set_response_status'
../libsimplecpu.so: undefined reference to `dlopen'
../libsimplecpu.so: undefined reference to `socket_target_register_b_transport'
../libsimplecpu.so: undefined reference to `payload_create'
../libsimplecpu.so: undefined reference to `payload_get_command'
../libsimplecpu.so: undefined reference to `tlm2c_socket_target_register_dmi'
../libsimplecpu.so: undefined reference to `tlm2c_bind'
../libsimplecpu.so: undefined reference to `payload_set_address'
../libsimplecpu.so: undefined reference to `dlclose'
../libsimplecpu.so: undefined reference to `payload_set_value'
../libsimplecpu.so: undefined reference to `dlerror'
../libsimplecpu.so: undefined reference to `dlsym'
../libsimplecpu.so: undefined reference to `model_notify'
../libsimplecpu.so: undefined reference to `payload_get_address'
../libsimplecpu.so: undefined reference to `socket_target_create'
../libsimplecpu.so: undefined reference to `socket_initiator_create'
../libsimplecpu.so: undefined reference to `payload_get_value'

Signed-off-by: Guillaume Delbergue <guillaume.delbergue@greensocs.com>

Conflicts:
	CMakeLists.txt